/**
 * Editorial category cards on /browse — labels are short; slugs map to `lib/topics` hubs.
 */
export const BROWSE_CATEGORY_CARDS: { label: string; slug: string }[] = [
  { label: "Gospel", slug: "gospel" },
  { label: "Grace", slug: "grace" },
  { label: "Anxiety", slug: "anxiety" },
  { label: "Fear", slug: "fear" },
  { label: "Faith", slug: "faith" },
  { label: "Trusting God", slug: "trusting-god" },
  { label: "Purpose", slug: "purpose" },
  { label: "Marriage", slug: "marriage" },
  { label: "Parenting", slug: "parenting" },
  { label: "Work", slug: "work" },
  { label: "Money", slug: "money" },
  { label: "Calling", slug: "calling" },
  { label: "Prayer", slug: "prayer" },
  { label: "Identity", slug: "identity" },
  { label: "Suffering", slug: "suffering" },
  { label: "Trials", slug: "trials" },
  { label: "Wisdom", slug: "wisdom" },
  { label: "End Times", slug: "end-times" },
  { label: "Discernment", slug: "discernment" },
  { label: "Doubt", slug: "doubt" },
  { label: "Obedience", slug: "obedience" },
  { label: "Repentance", slug: "repentance" },
  { label: "Forgiveness", slug: "forgiveness" },
  { label: "Worship", slug: "worship" },
  { label: "Church History", slug: "church-history" },
  { label: "Spiritual Growth", slug: "spiritual-growth" },
];
